functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Нужно разработать интерфейс интернет-магазина с просмотром и фильтрацией товаров, а также добавлением их в корзину.
  - На странице корзины пользователь cможет удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты. Корзина будет хранится в сессии браузера.
  - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее. Пользователь будет добавлять товар в корзину и продолжать выбирать товары в каталоге.
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Ключевой возможностью магазина будет адаптивная верстка, чтобы он был удобным на мобильных устройствах. Также магазин будет SPA-приложение, которое не перезагружает страницу. Пользователь будет просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом.
implicit:
  - При нажатии на товар открывается карточка товара, на той же вкладке, не открывая новую.
  - Цена товара не должна быть отрицательной
  - Невозможно заказать товар, которого нет в наличии
  - Если пользователь выбирает фильтры, по которым не находится товар, отображается уведомление "Ничего не найдено!"
  - Сайт должен быть удобным и понятным для пользователя. 
  - Фотографии товаров должны быть качественными и показывать товар с разных сторон
